### PR TITLE
housekeeping: Minor update

### PR DESCRIPTION
**Pull request by weitzhandler**
Minor clarification in README, it sounds like this project has dependencies on other projects, clarified that.

### CODE REVIEW

**Comment by glennawatson** [comment]
I might of said "Original implementation based on ..."

**Comment by weitzhandler** [comment]
I see It's already been merged, feel free to update or lemme know if I should.

**Comment by glennawatson** [comment]
Go ahead if you like and I'll approve again quickly.

**Comment by weitzhandler** [comment]
Does that mean opening a new PR?

**Comment by weitzhandler** [comment]
#7

**Pull request merged**
